# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mail_parser"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jimmy Chao"]
  s.date = "2012-03-19"
  s.description = "Parser for parsing imformation by regex in mail"
  s.email = ""
  s.files = [
    "lib/mail_parser.rb",
    "lib/mail_parser/mail_parser.rb",
    "lib/samples/mail_loader.rb"
  ]
  s.homepage = "http://github.com/Rafe/mail_parser"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.19"
  s.summary = "Parser for parsing imformation by regex in mail"
  s.test_files = ["spec/*.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

