# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mail_parser"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jimmy Chao"]
  s.date = "2012-03-20"
  s.description = "Parser for parsing imformation by regex in mail"
  s.email = ""
  s.files = [
    "lib/mail_loader.rb",
    "lib/mail_parser.rb",
    "lib/mail_parser/mail_parser.rb",
    "lib/patterns/amazon_pattern.rb",
    "lib/patterns/pattern.rb"
  ]
  s.homepage = "http://github.com/Rafe/mail_parser"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.19"
  s.summary = "Parser for parsing imformation by regex in mail"
  s.test_files = ["spec/amazon_pattern_spec.rb", "spec/mail_parser_spec.rb", "spec/pattern_spec.rb", "spec/spec_helper.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mail_parser>, [">= 0"])
    else
      s.add_dependency(%q<mail_parser>, [">= 0"])
    end
  else
    s.add_dependency(%q<mail_parser>, [">= 0"])
  end
end

